name: 03 - Workflow Runners
on: push

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show Ubuntu OS
        run: |
          echo "This job is running on an Ubuntu runner"
          echo "Runner OS: $RUNNER_OS"

  windows-job:
    runs-on: windows-latest
    steps:
      - name: Show Windows OS
        shell: bash
        run: |
          echo "This job is running on an Windows runner"
          echo "Runner OS: $RUNNER_OS"

  mac-job:
    runs-on: macos-latest
    steps:
      - name: Show MACOS
        run: |
          echo "This job is running on an MACOS runner"
          echo "Runner OS: $RUNNER_OS"