name: My workflow
on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "First job"

  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Second job"

  suceed-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: |
          echo "I will suceed"
          exit 0

      - name: Say Goodbye
        run: echo "Goodbye!"